sensor:  
  - platform: ld2410
    light:
      name: Jasność
    moving_distance:
      name: Dystans celu w ruchu
    still_distance:
      name: Dystans celu w spoczynku
    moving_energy:
      name: Energia ruchu
    still_energy:
      name: Energia spoczynkowa
    detection_distance:
      name: Odległość detekcji
    g0:
      move_energy:
        name: g0 Energia ruchu
      still_energy:
        name: g0 Energia spoczynkowa
    g1:
      move_energy:
        name: g1 Energia ruchu
      still_energy:
        name: g1 Energia spoczynkowa
    g2:
      move_energy:
        name: g2 Energia ruchu
      still_energy:
        name: g2 Energia spoczynkowa
    g3:
      move_energy:
        name: g3 Energia ruchu
      still_energy:
        name: g3 Energia spoczynkowa
    g4:
      move_energy:
        name: g4 Energia ruchu
      still_energy:
        name: g4 Energia spoczynkowa
    g5:
      move_energy:
        name: g5 Energia ruchu
      still_energy:
        name: g5 Energia spoczynkowa
    g6:
      move_energy:
        name: g6 Energia ruchu
      still_energy:
        name: g6 Energia spoczynkowa
    g7:
      move_energy:
        name: g7 Energia ruchu
      still_energy:
        name: g7 Energia spoczynkowa
    g8:
      move_energy:
        name: g8 Energia ruchu
      still_energy:
        name: g8 Energia spoczynkowa

binary_sensor:
  - platform: ld2410
    has_target:
      name: Obecność
    has_moving_target:
      name: Obecność w ruchu
    has_still_target:
      name: Obecność w spoczynku
    out_pin_presence_status:
      name: Obecność na wyjściu

switch:
  - platform: ld2410
    engineering_mode:
      name: Kalibracja
    bluetooth:
      name: Bluetooth

number:
  - platform: ld2410
    timeout:
      name: limit czasu odpowiedzi
    light_threshold:
      name: Próg światła
    max_move_distance_gate:
      name: maksymalny dystans ruchu
    max_still_distance_gate:
      name: maksymalny dystans spoczynku
    g0:
      move_threshold:
        name: g0 Próg ruchu
      still_threshold:
        name: g0 Próg spoczynku
    g1:
      move_threshold:
        name: g1 Próg ruchu
      still_threshold:
        name: g1 Próg spoczynku
    g2:
      move_threshold:
        name: g2 Próg ruchu
      still_threshold:
        name: g2 Próg spoczynku
    g3:
      move_threshold:
        name: g3 Próg ruchu
      still_threshold:
        name: g3 Próg spoczynku
    g4:
      move_threshold:
        name: g4 Próg ruchu
      still_threshold:
        name: g4 Próg spoczynku
    g5:
      move_threshold:
        name: g5 Próg ruchu
      still_threshold:
        name: g5 Próg spoczynku
    g6:
      move_threshold:
        name: g6 Próg ruchu
      still_threshold:
        name: g6 Próg spoczynku
    g7:
      move_threshold:
        name: g7 Próg ruchu
      still_threshold:
        name: g7 Próg spoczynku
    g8:
      move_threshold:
        name: g8 Próg ruchu
      still_threshold:
        name: g8 Próg spoczynku

button:
  - platform: ld2410
    factory_reset:
      name: Reset
    restart:
      name: Restarts
    query_params:
      name: Odpytaj Parametry

text_sensor:
  - platform: ld2410
    version:
      name: Wersja Oprogramowania
    mac_address:
      name: Adres MAC

select:
  - platform: ld2410
    distance_resolution:
      name: Rodzielczość
    baud_rate:
      name: Szybkość Transmisji
    light_function:
      name: Detekcja Światła
    out_pin_level:
      name: Poziom wyjścia
